# Configure firehose event types to log
- type: replace
  path: /instance_groups/name=ingestor/jobs/name=ingestor_cloudfoundry-firehose/properties/cloudfoundry/firehose_events?
  value: 
    - ContainerMetric
    - CounterEvent
    - Error
    - HttpStartStop
    - LogMessage
    - ValueMetric

# Configure firehose event types used to create dashboards 
- type: replace
  path: /instance_groups/name=upload-kibana-objects/jobs/name=upload-kibana-objects/properties?/cloudfoundry?/firehose_events?
  value: 
    - ContainerMetric
    - CounterEvent
    - Error
    - HttpStartStop
    - LogMessage
    - ValueMetric



# Set the reload time of metadata from the cloud controller (org/space/app names)
- type: replace
  path: /instance_groups/name=ingestor/jobs/name=ingestor_cloudfoundry-firehose/properties/cloudfoundry/firehose_cc_pull_interval?
  value: "300s"

# Set subscription ID to be unique
- type: replace
  path: /instance_groups/name=ingestor/jobs/name=ingestor_cloudfoundry-firehose/properties/cloudfoundry/firehose_subscription_id?
  value: logsearch-firehose-sub-id


